dist: xenial
sudo: required
language: c

branches:
  only:
  - v8.8
  - v8.9
  - v8.9+worker
  - v8.10

cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    packages:
    - gcc-multilib
env:
  global:
  - NJOBS=2
  - OPAMROOTISOK="true"
  - OPAMYES="true"
  - OPAMJOBS="2"
  - COMPILER="4.07.1+32bit"
  - BASE_OPAM="camlp5 dune"
  # We will have more targets later on for sure;
  # matrix:
  #   - COMPILER="4.07.1+32bit"

matrix:
  include:
    - dist: xenial
    - os: osx
      cache:
        ccache: true
        directories:
          - $HOME/.opam
          - $HOME/Library/Caches/Homebrew
      before_cache:
        - brew cleanup
      before_install: |
        set -e
        brew update
        brew install ccache opam

before_install: |
  sudo curl -sL https://github.com/ocaml/opam/releases/download/2.0.1/opam-2.0.1-x86_64-linux -o /usr/bin/opam
  sudo chmod 755 /usr/bin/opam

install:
- opam init -c "$COMPILER" --disable-sandboxing
- opam switch set "$COMPILER"
- eval $(opam env)
- opam install $BASE_OPAM
- opam list
- opam update
- opam config var root
- ./toolchain-setup.sh
- opam list
- make coq-get
- make coq-build

script:
- echo 'Building JsCoq...' && echo -en 'travis_fold:start:jscoq.build\\r'
- ./build.sh
- git submodule update --remote
- cd ui-external/CodeMirror && npm install
- echo -en 'travis_fold:end:jscoq.build\\r'
